### ISSUE TITLE
Default value for parameters with type array not taken into account

### ISSUE THREAD

**Issue by vinassefranche** [apigee-127/sway#132]
Hi,

If we define a global default value for a parameter with type array, the default value will never be used, even if no default value is set for the items.

For a parameter defined like this :
```
fields:
    name: fields
    in: query
    type: array
    items:
      type: string
    required: false
    default: ["uuid", "name", "value"]
```
if i call the api without specifying the fields parameter in the query, `request.swagger.params.fields.value` will remain `undefined`. I would expect it to be `["uuid", "name", "value"]`

I've seen in the code that you expect default values to be set in the items definitions and never fall back to the global default. It prevents me from having a default value with more than one item in it in my example.

If you agree that somehow this default value should be used, there would be 2 ways of doing it:
- check first for the presence of the global default value and use it if present. It means that the potential default values of the items would never be used.
- process the default values of the items and if the result is still undefined and if there is a global default value, use this value.

The first option would suit my needs better but i'm open to both of them.

I've coded both options on my computer so i can contribute to the project if needed. Feel free to ask me.

Regards
