### ISSUE TITLE
no validation error when `allowEmptyValue` is set to `false` and param is left empty

### ISSUE THREAD

**Issue by rhbecker** [apigee-127/sway#88]
In response to issue #27, _some_ support for the `allowEmptyValue` param constraint was introduced, but seemingly only in support of the `true` scenario. Am I misunderstanding the spec or the sway codebase if I suggest that a validation error should be produced when the value is set to `false` and an empty value is passed in by a client?
### reproduction recipe
1. Add some swagger config like:
   
   ``` yaml
   get:
     parameters:
       - name: q
         in: query
         type: string
         required: true
         allowEmptyValue: false
   ```
2. Include the `q` param in your request's query string, but leave it empty.
### what happens

no validation error
### what is expected

a validation error
